language: ruby
cache: bundler
dist: trusty
sudo: false
before_script:
  - travis_retry gem install rails --version '~> 5.1.0'

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
